services:
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    image: amoghk22/officedesk-backend:latest
    ports:
      - "8084:8084"
    environment:
      TZ: Asia/Kolkata
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JACKSON_TIME_ZONE: Asia/Kolkata
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

  frontend:
    image: amoghk22/officedesk-frontend:latest
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  pgdata:
