spring.application.name=officedesk

spring.datasource.url=jdbc:postgresql://localhost:5432/officedesk
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Amogh45_@

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=Xp7!kL9$mQ2@wR5&jN8#cV4^bH6*fT3%aG0!dS7~eU1+yI9-oA5@pE2\$sD4%rF8(gK6)
jwt.expiration=86400000

server.port=8084
